// English

export default {
    //main.ts
    'Open Dictionary View': 'Open Dictionary View',
    'Open Language Switcher': 'Open Language Switcher',

    //_constants.ts
    'Dictionary': 'Dictionary',

    //customContextMenu.ts
    'Cut': 'Cut',
    'Copy': 'Copy',
    'Paste': 'Paste',
    'Show Synonyms': 'Show Synonyms',
    'Look up': 'Look up',

    //settingsTab.ts
    'Dictionary Settings': 'Dictionary Settings',
    'Language': 'Language',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': 'The Language the Plugin will use to search for Definitions and Pronunciations.',
    'Synonym Suggestions': 'Synonym Suggestions',
    'Show synonyms for highlighted words': 'Show synonyms for highlighted words',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.',
    'Click ': 'Click ',
    'here': 'here',
    ' for Privacy Concerns.': ' for Privacy Concerns.',
    'Advanced Synonym Search': 'Advanced Synonym Search',
    'Show Options in Context Menu': 'Show Options in Context Menu',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu. To ensure compatibility with other Plugins please install the "Extended Context Menu" Plugin.',
    'Click Here': 'Click Here',
    'Definition Provider': 'Definition Provider',
    'The API the Plugin will use to search for Definitions.': 'The API the Plugin will use to search for Definitions.',
    'Synonym Provider': 'Synonym Provider',
    'The API the Plugin will use to search for Synonyms.': 'The API the Plugin will use to search for Synonyms.',
    'More Information': 'More Information',
    'View Information about the API\'s and the Plugin itself.': 'View Information about the API\'s and the Plugin itself.',
    'More Info': 'More Info',
    'Donate': 'Donate',
    'If you like this Plugin, consider donating to support continued development:': 'If you like this Plugin, consider donating to support continued development:',
    'Local Dictionary Folder': 'Local Dictionary Folder',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': 'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.',
    'Capitalize File Name': 'Capitalize File Name',
    'If you disable this, the names of newly created files will be all lowercase.': 'If you disable this, the names of newly created files will be all lowercase.',
    'Filename Prefix and Suffix': 'Filename Prefix and Suffix',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'Here you can add a Prefix and Suffix for your newly created Files.',
    "Prefix": "Prefix",
    "Suffix": "Suffix",
    'Here you can edit the Template for newly created Files.': 'Here you can edit the Template for newly created Files.',
    'Click for a List of Variables': 'Click for a List of Variables',
    'Template': 'Template',
    "Local-Dictionary-Builder Settings": "Local-Dictionary-Builder Settings",
    "Miscellaneous": "Miscellaneous",
    

    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Autogenerated by Obsidian Dictionary Plugin',
    

    //infoModal.svelte
    'API Information': 'API Information',
    'Definition API\'s': 'Definition API\'s',
    'Website': 'Website',
    'Synonym API\'s': 'Synonym API\'s',
    'Part of Speech API\'s': 'Part of Speech API\'s',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>',

    //dictionaryView.svelte
    'Enter a word': 'Enter a word',
    'Pronunciation': 'Pronunciation',
    'Meanings': 'Meanings',
    'New Note': 'New Note',

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': 'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.',

    //meaningComponent.ts
    'Definition:': 'Definition:',
    'Synonyms:': 'Synonyms:',

    //modals
    "Choose a Definition Provider Service": "Choose a Definition Provider Service",
    "Choose a Language": "Choose a Language",
    "Choose a Synonym Provider Service": "Choose a Synonym Provider Service",
};
