// Español

export default {
    //main.ts
    'Open Dictionary View': 'Abrir vista de Diccionario',
    'Open Language Switcher': 'Abrir Selector de Idioma',

    //_constants.ts
    'Dictionary': 'Diccionario',

    //customContextMenu.ts
    'Cut': 'Cortar',
    'Copy': 'Copiar',
    'Paste': 'Pegar',
    'Show Synonyms': 'Mostrar Sinónimos',
    'Look up': 'Buscar',

    //settingsTab.ts
    "Reset to default": "Resetear a configuración por defecto",
    'Dictionary Settings': 'Configuración del Diccionario',
    'Language': 'Idioma',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': 'El Idioma que el Plugin usará para buscar Definiciones y Pronunciaciones.',
    'Synonym Suggestions': 'Sugerencias de Sinónimos',
    'Show synonyms for highlighted words': 'Mostrar sinónimos para palabras resaltadas',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'Activar esto habilitará al plugin para analizar frases enteras para sugerir mejores sinónimos basándose en el contexto.',
    'Click ': 'Click ',
    'here': 'aquí',
    ' for Privacy Concerns.': ' for Privacy Concerns.',
    'Advanced Synonym Search': 'Búsqueda Avanzada de Sinónimos',
    'Show Options in Context Menu': 'Mostrar opciones en el Menú Contextual',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'Habilitar el Menú Contextual personalizado con opciones para buscar sinónimos (sólo si las sugerencias automáticas están deshabilitadas) y para buscar una definición completa en la Barra Lateral.',
    'Click Here': 'Clica Aquí',
    'Definition Provider': 'Proveedor de Definiciones',
    'The API the Plugin will use to search for Definitions.': 'La API que el Plugin utilizará para buscar Definiciones.',
    'Synonym Provider': 'Proveedor de Sinónimos',
    'The API the Plugin will use to search for Synonyms.': 'La API que el Plugin utilizará para buscar Sinónimos.',
    'More Information': 'Más Información',
    'View Information about the API\'s and the Plugin itself.': 'Ver información sobre la API y el propio Plugin.',
    'More Info': 'Más Info',
    'Donate': 'Donar',
    'If you like this Plugin, consider donating to support continued development:': 'Si te gusta este Plugin, considera donar para apoyar un desarrollo contínuo:',
    'Local Dictionary Folder': 'Carpeta del Diccionario Local',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': 'Especifica una Carpeta, donde se encuentran todas las nuevas Notas creadas por el Diccionario. La Carpeta debe existir.',
    'Capitalize File Name': 'Capitaliar Nombre de Fichero',
    'If you disable this, the names of newly created files will be all lowercase.': 'Si desactivas esto, los nombres de nuevos ficheros estarán en minúsculas.',
    'Filename Prefix and Suffix': 'Prefijo y Sufijo del Nombre del Fichero',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'Aquí puedes añadir un Prefijo y un Sufijo para los nuevos Ficheros creados. Puedes utilizar la variable {{lang}}.',
    "Prefix": "Prefijo",
    "Suffix": "Sufijo",
    'Here you can edit the Template for newly created Files.': 'Aquí puedes editar la Plantilla nuevos Ficheros',
    'Click for a List of Variables': 'Clica para una Lista de Variables',
    'Template': 'Plantilla',
    "Local-Dictionary-Builder Settings": "Configuración del Builder del Diccionario Local",
    "Miscellaneous": "Misceláneo",
    "Caching Settings": "Caché de Configuraciones",
    "Use Caching": "Utilizar Caché",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "Activar o desactivar Caché. La memoria Caché proporciona una experiencia semi-offline al guardar cada resultado para utilizarlo más tarde.",
    'Here you can delete all cached Data.': 'Aquí puedes borrar todos los datos en Caché.',
    "You currently have ": "Actualmente tienes ",
    " cached Definitions and ": " Definiciones y ",
    " cached Synonyms.": " Sinónimos en Caché.",
    "Delete Cache": "Borrar Caché",
    "Delete": "Borrar",
    "Success": "Éxito",
    'Use Language specific Subfolders': 'Utilizar Subcarpetas por cada Idioma',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': 'Crear una Subcarpeta por cada Idioma. P.E.: "Dictionary/en-US/Cake"',


    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Autogenerado por Obsidian Dictionary Plugin',
    "Yes, overwrite the old File.": "Sí, sobreescribir el fichero antigüo.",
    "A existing File with the same Name was found, do you want to overwrite it?": "Se ha encontrado un Fichero con el mismo nombre. ¿Desea sobreescribirlo?",
    "No, keep the old File.": "No, conservar el Fichero antigüo.",
    "Meaning {{i}}": "Significa {{i}}",


    //infoModal.svelte
    'API Information': 'Información de la API',
    'Definition API\'s': 'API de Definiciones',
    'Website': 'Página Web',
    'Synonym API\'s': 'API de Sinónimos',
    'Part of Speech API\'s': 'Part of Speech API\'s',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'Este Plugin utiliza <a href="https://feathericons.com/">Feather Icons</a>',

    //dictionaryView.svelte
    'Enter a word': 'Introduce una palabra',
    "Clear": "Limpiar",
    "Change Language": "Cambiar Idioma",
    "Change Provider": "Cambiar Proveedor",
    "Collapse Results": "Colapsar Resultados",
    'Pronunciation': 'Pronunciación',
    'Meanings': 'Significados',
    "Origin": "Etimología",
    'New Note': 'Nueva Nota',
    "View Error": "Ver Error",
    "Match Case": "Match Case",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\" copiada al portapapeles",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': 'No puedo encontrar la palabra que buscas, o bien no se puede contactar con el servidor. Vuelve a intentarlo dentro de unos minutos.',

    //meaningComponent.ts
    'Definition:': 'Definición:',
    'Synonyms:': 'Sinónimos:',
    'Antonyms:': 'Antónimos:',

    //modals
    "Choose a Definition Provider Service": "Elige un Servicio de Provisión de Definiciones",
    "Choose a Language": "Elige un Idioma",
    "Choose a Synonym Provider Service": "Elige un Servicio de Provisión de Sinónimos",
};
