// 日本語

export default {
    //main.ts
    'Open Dictionary View': '辞書を開く',
    'Open Language Switcher': '言語スイッチャーを開く',

    //_constants.ts
    'Dictionary': '辞書',

    //customContextMenu.ts
    'Cut': 'カット',
    'Copy': 'コピー',
    'Paste': 'ペースト',
    'Show Synonyms': '同義語を表示',
    'Look up': '辞書で検索',

    //settingsTab.ts
    "Reset to default": "デフォルトにリセットする",
    'Dictionary Settings': '辞書設定',
    'Language': '言語',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': '語義と発音の検索に使用する言語を選択してください。',
    'Synonym Suggestions': '同義語のサジェスト',
    'Show synonyms for highlighted words': 'ハイライトされた単語の同義語を表示します。',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'このオプションを有効化すると、文章の完全解析とその内容に基づいた同義語のサジェストを行います。',
    'Click ': 'クリック ',
    'here': 'これ',
    ' for Privacy Concerns.': ' プライバシーについて',
    'Advanced Synonym Search': '高度な同義語検索',
    'Show Options in Context Menu': 'コンテキストメニューでのオプション表示',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'カスタムコンテキストメニューでの同義語検索オプションを有効化します。(自動サジェストが無効化されている場合のみ)サイドバーで完全な語義を調べることができます。',
    'Click Here': 'ここをクリック',
    'Definition Provider': '語義プロバイダ',
    'The API the Plugin will use to search for Definitions.': 'プラグインが語義の検索に使用するAPIを選択してください。',
    'Synonym Provider': '同義語プロバイダ',
    'The API the Plugin will use to search for Synonyms.': 'プラグインが同義語の検索に使用するAPIを選択してください。',
    'More Information': '詳しい情報',
    'View Information about the API\'s and the Plugin itself.': 'APIとプラグインについての情報を閲覧できます。',
    'More Info': '更に詳しく',
    'Donate': '寄付する',
    'If you like this Plugin, consider donating to support continued development:': 'このプラグインが気に入った場合には、継続的な開発のサポートのための寄付を検討してみてください。',
    'Local Dictionary Folder': 'ローカル辞書フォルダ',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': '辞書により作成された新規ノートが配置されるフォルダを指定してください。すでに存在するフォルダを指定してください。',
    'Capitalize File Name': 'ファイル名を大文字から始めて作成する',
    'If you disable this, the names of newly created files will be all lowercase.': 'このオプションを無効化すると新規作成されたファイル名はすべて小文字になります。',
    'Filename Prefix and Suffix': 'ファイル名のプレフィックスとサフィックス',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'このオプションでは、新規作成されるファイルに対してプレフィックスまたはサフィックスを追加することができます。この項目では{{lang}}変数を使用できます。',
    "Prefix": "プレフィックス",
    "Suffix": "サフィックス",
    'Here you can edit the Template for newly created Files.': 'このオプションでは新規作成されるファイルについてのテンプレートを編集できます。',
    'Click for a List of Variables': '変数のリストを閲覧する',
    'Template': 'テンプレート',
    "Local-Dictionary-Builder Settings": "ローカル辞書ビルダーの設定",
    "Miscellaneous": "その他のオプション",
    "Caching Settings": "キャッシュの設定",
    "Use Caching": "キャッシュを使用する",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "キャッシュの使用を選択できます。キャッシュを有効化するとすべての検索結果を保存しておき、後からセミオフラインでの機能提供が可能です。",
    'Here you can delete all cached Data.': 'このオプションですべてのキャッシュデータを削除することができます。',
    "You currently have ": "現在、次の項目をキャッシュしています: ",
    " cached Definitions and ": " 語義 ",
    " cached Synonyms.": " 同義語",
    "Delete Cache": "キャッシュの削除",
    "Delete": "削除する",
    "Success": "成功しました",
    'Use Language specific Subfolders': '特定言語のサブフォルダを使用する',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': '指定の言語についてのサブフォルダを作成します。例: "Dictionary/en-US/Cake"',


    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Obsidian Dictionary Pluginによって自動生成されています',
    "Yes, overwrite the old File.": "はい、古いファイルを上書きします。",
    "A existing File with the same Name was found, do you want to overwrite it?": "同一名の既存ファイルが見つかりました。新しい内容で上書きしますか？",
    "No, keep the old File.": "いいえ、古いファイルは保存してください。",
    "Meaning {{i}}": "意味 {{i}}",


    //infoModal.svelte
    'API Information': 'APIについての情報',
    'Definition API\'s': '語義API',
    'Website': 'ウェブサイト',
    'Synonym API\'s': '同義語API',
    'Part of Speech API\'s': '品詞API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'このプラグインは<a href="https://feathericons.com/">Feather Icons</a>を使用しています',

    //dictionaryView.svelte
    'Enter a word': '単語を入力',
    "Clear": "クリア",
    "Change Language": "言語を変更",
    "Change Provider": "プロバイダを変更",
    "Collapse Results": "結果を展開",
    'Pronunciation': '発音',
    'Meanings': '意味',
    "Origin": "語源",
    'New Note': '新規ノート',
    "View Error": "エラーを表示",
    "Match Case": "大文字/小文字を区別",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\"をクリップボードにコピーしました",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': '探している単語が見つからないか、サーバーが接続できません。数分立ってからリトライしてください。',

    //meaningComponent.ts
    'Definition:': '語義:',
    'Synonyms:': '同義語:',
    'Antonyms:': '反意語:',

    //modals
    "Choose a Definition Provider Service": "定義のプロバイダサービスを選択",
    "Choose a Language": "言語を選択",
    "Choose a Synonym Provider Service": "同義語のプロバイダサービスを選択",
};
