// 한국어

export default {
    //main.ts
    'Open Dictionary View': '사전 보기 열기',
    'Open Language Switcher': '언어 전환 열기',

    //_constants.ts
    'Dictionary': '사전',

    //customContextMenu.ts
    'Cut': '잘라내기',
    'Copy': '복사',
    'Paste': '붙여넣기',
    'Show Synonyms': '유의어 표시',
    'Look up': '찾기',

    //settingsTab.ts
    "Reset to default": "기본값으로 재설정",
    'Dictionary Settings': '사전 설정',
    'Language': '언어',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': '사전 정의 및 발음 검색을 위한 언어입니다.',
    'Synonym Suggestions': '유의어 제안',
    'Show synonyms for highlighted words': '강조된 단어의 유의어를 표시합니다.',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': '활성화 시 전체 문장을 분석하여 컨텍스트를 기반으로 유의어를 더 잘 제안할 수 있습니다.',
    'Click ': 'Click ',
    'here': 'here',
    ' for Privacy Concerns.': ' for Privacy Concerns.',
    'Advanced Synonym Search': '고급 유의어 검색',
    'Show Options in Context Menu': '상황에 맞는 메뉴 표시',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': '자동 제안이 비활성화된 경우에만 동의어를 검색하고 사이드바에서 전체 정의를 조회하는 맞춤 컨텍스트 메뉴를 활성화합니다.',
    'Click Here': '여기를 클릭하세요.',
    'Definition Provider': '사전 정의 제공자',
    'The API the Plugin will use to search for Definitions.': '사전 정의 검색에 사용할 API',
    'Synonym Provider': '유의어 제공자',
    'The API the Plugin will use to search for Synonyms.': '유의어 검색에 사용할 API',
    'More Information': 'More Information',
    'View Information about the API\'s and the Plugin itself.': 'API 및 플러그인 대한 정보를 봅니다.',
    'More Info': '더보기',
    'Donate': '기부',
    'If you like this Plugin, consider donating to support continued development:': '이 플러그인이 맘에든다면 지속적으로 개발할 수 있도록 기부해 주세요.',
    'Local Dictionary Folder': '로컬 사전 폴더',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': '사전이 만들어질 폴더를 지정하세요. 참고로 이 폴더는 사전에 만들어져 있어야 합니다.',
    'Capitalize File Name': '대문자 파일명',
    'If you disable this, the names of newly created files will be all lowercase.': '비활성화 시 새로 작성된 파일명은 소문자로 작성됩니다.',
    'Filename Prefix and Suffix': '파일명 접두사 및 접미어',
    'Here you can add a Prefix and Suffix for your newly created Files.': '새로 만들어진 파일의 접두사 및 접미어를 추가할 수 있습니다. {{lang}} 변수를 사용할 수 있습니다.',
    "Prefix": "접두사",
    "Suffix": "접미어",
    'Here you can edit the Template for newly created Files.': '새로 만들어진 파일의 템플릿을 수정할 수 있습니다.',
    'Click for a List of Variables': '변수 목록 보러가기',
    'Template': '템플릿',
    "Local-Dictionary-Builder Settings": "Local-Dictionary-Builder 설정",
    "Miscellaneous": "기타",
    "Caching Settings": "캐싱 설정",
    "Use Caching": "캐싱 사용",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "캐싱을 활성화하거나 비활성화합니다. 캐싱은 나중에 사용할 수 있도록 모든 결과를 저장하여 세미 오프라인 환경을 제공합니다.",
    'Here you can delete all cached Data.': '캐시된 데이터를 모두 삭제할 수 있습니다.',
    "You currently have ": "현재 ",
    " cached Definitions and ": "개의 캐쉬된 사전정의 및 ",
    " cached Synonyms.": "개의 캐쉬된 유의어가 있습니다.",
    "Delete Cache": "캐쉬 삭제",
    "Delete": "삭제",
    "Success": "성공",
    'Use Language specific Subfolders': '언어별 하위 폴더 사용',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': '언어별로 하위 폴더를 생성합니다. 예) "Dictionary/en-US/Cake"',


    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Obsidian 사전 플러그인에 의해 자동 생성',
    "Yes, overwrite the old File.": "네, 이전 파일을 덮어씁니다.",
    "A existing File with the same Name was found, do you want to overwrite it?": "동일한 이름의 기존 파일을 찾았습니다. 덮어쓰시겠습니까?",
    "No, keep the old File.": "아니요, 이전 파일을 유지합니다.",
    "Meaning {{i}}": "의미 {{i}}",


    //infoModal.svelte
    'API Information': 'API 정보',
    'Definition API\'s': '사전 정의 API',
    'Website': '웹사이트',
    'Synonym API\'s': '유의어 API',
    'Part of Speech API\'s': '음성 API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': '이 플러그인은 <a href="https://feathericons.com/">Feather Icons</a>을 사용합니다.',

    //dictionaryView.svelte
    'Enter a word': '단어를 입력하세요.',
    "Clear": "Clear",
    "Change Language": "언어 변경",
    "Change Provider": "Change Provider",
    "Collapse Results": "결과 접기",
    'Pronunciation': '발음',
    'Meanings': '의미',
    "Origin": "기원",
    'New Note': '신규 노트',
    "View Error": "오류 보기",
    "Match Case": "대소문자 구분",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\"를 클립보드에 복사되었습니다.",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': '단어를 찾을 수 없거나 서버가 연결되지 않습니다. 잠시 후 다시 시도해 보세요.',

    //meaningComponent.ts
    'Definition:': '사전 정의 :',
    'Synonyms:': '유의어:',
    'Antonyms:': '반의어:',

    //modals
    "Choose a Definition Provider Service": "사전 정의 제공 서비스를 선택하세요.",
    "Choose a Language": "언어를 선택하세요.",
    "Choose a Synonym Provider Service": "유의어 제공 서비스를 선택하세요.",
};
