// русский

export default {
    //main.ts
    'Open Dictionary View': 'Открыть Меню Словаря',
    'Open Language Switcher': 'Открыть Выбор Языка',

    //_constants.ts
    'Dictionary': 'Словарь',

    //customContextMenu.ts
    'Cut': 'Вырезать',
    'Copy': 'Скопировать',
    'Paste': 'Вставить',
    'Show Synonyms': 'Показать Синонимы',
    'Look up': 'Найти',

    //settingsTab.ts
    "Reset to default": "Сбросить к настройкам по умолчанию",
    'Dictionary Settings': 'Настройки Словаря',
    'Language': 'Язык',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': 'Язык, который будет использован плагином при поиске определений и произношения.',
    'Synonym Suggestions': 'Предложение Синонимов',
    'Show synonyms for highlighted words': 'Показывать синонимы для выделенных слов',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'Включение этой опции позволяет плагину анализировать предложения целиком для предложения более подходящие синонимов в зависимости от контекста.',
    'Click ': 'Нажмите ',
    'here': 'сюда',
    ' for Privacy Concerns.': ' для информации о конфиденциальности.',
    'Advanced Synonym Search': 'Продвинутый Поиск Синонимов',
    'Show Options in Context Menu': 'Показывать функции в контекстном меню',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'Добавить в контекстное меню возможность поиска синонимов (только при выключенном автодополнении) и возможность просмотра полного определения в боковом меню.',
    'Click Here': 'Нажмите Сюда',
    'Definition Provider': 'Провайдер Определений',
    'The API the Plugin will use to search for Definitions.': 'API, который будет использован плагином для поиска определений.',
    'Synonym Provider': 'Провайдер Синонимов',
    'The API the Plugin will use to search for Synonyms.': 'API, который будет использован плагином для поиска синонимов.',
    'More Information': 'Дополнительная Информация',
    'View Information about the API\'s and the Plugin itself.': 'Информация об используемых API и о самом плагине.',
    'More Info': 'Узнать Подробнее',
    'Donate': 'Пожертвовать',
    'If you like this Plugin, consider donating to support continued development:': 'Если вам нравится плагин, рассмотрите возможность пожертвования дальнейшую его разработку:',
    'Local Dictionary Folder': 'Директория Локального Словаря',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': 'Укажите директорию, в которой будут создаваться все новые заметки, созданные Словарём. Пожалуйста, учтите, что директория должна существовать.',
    'Capitalize File Name': 'Начинать Слова в Названии Файлов с Заглавной Буквы',
    'If you disable this, the names of newly created files will be all lowercase.': 'Если вы выключите эту опцию, названия в созданных файлах будут начинаться с маленьких букв.',
    'Filename Prefix and Suffix': 'Префикс и суффикс названий файлов',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'Здесь вы можете задать префикс и суффикс для создаваемых файлов. Можно использовать переменную {{lang}}.',
    "Prefix": "Префикс",
    "Suffix": "Суффикс",
    'Here you can edit the Template for newly created Files.': 'Здесь можно редактировать шаблон для создаваемых файлов.',
    'Click for a List of Variables': 'Нажмите сюда, чтобы перейти к списку переменных',
    'Template': 'Шаблон',
    "Local-Dictionary-Builder Settings": "Настройки Создания Локального Словаря",
    "Miscellaneous": "Разное",
    "Caching Settings": "настройки Кэширования",
    "Use Caching": "Использовать Кэширование",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "Включить или выключить кэширование. Кэширование обеспечивает полуавтономную работу, где каждый результат сохраняется для дальнейшего использования.",
    'Here you can delete all cached Data.': 'Здесь можно удалить все кэшированные данные.',
    "You currently have ": "У вас сейчас ",
    " cached Definitions and ": " кэшированных определений и ",
    " cached Synonyms.": " кэшированных синонимов.",
    "Delete Cache": "Удалить кэш",
    "Delete": "Удалить",
    "Success": "Успех",
    'Use Language specific Subfolders': 'Использовать поддиректории для языков',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': 'Создавать поддиректории для каждого языка, т.е. "Dictionary/en-US/Cake"',


    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Сгенерировано плагином Obsidian Dictionary',
    "Yes, overwrite the old File.": "Да, перезаписать старый файл.",
    "A existing File with the same Name was found, do you want to overwrite it?": "Файл с таким именем уже существует, хотите ли вы его перезаписать?",
    "No, keep the old File.": "Нет, оставить старый файл.",
    "Meaning {{i}}": "Значение {{i}}",


    //infoModal.svelte
    'API Information': 'Информация об API',
    'Definition API\'s': 'API Определений',
    'Website': 'Сайт',
    'Synonym API\'s': 'API Синонимов',
    'Part of Speech API\'s': 'Часть Speech API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'Этот плагин использует <a href="https://feathericons.com/">Feather Icons</a>',

    //dictionaryView.svelte
    'Enter a word': 'Введите слово',
    "Clear": "Очистить",
    "Change Language": "Изменить Язык",
    "Change Provider": "Сменить Провайдера",
    "Collapse Results": "Свернуть Результаты",
    'Pronunciation': 'Произношение',
    'Meanings': 'Значения',
    "Origin": "Происхождение",
    'New Note': 'Новая Заметка',
    "View Error": "Увидеть ошибку",
    "Match Case": "Учитывать Регистр",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\" скопировано в буфер обмена",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': 'Не удалось найти слово или сервер не доступен. Вы можете попробовать ещё раз через несколько минут.',

    //meaningComponent.ts
    'Definition:': 'Определение:',
    'Synonyms:': 'Синонимы:',
    'Antonyms:': 'Антонимы:',

    //modals
    "Choose a Definition Provider Service": "Выберите провайдера определений",
    "Choose a Language": "Выберите язык",
    "Choose a Synonym Provider Service": "Выберите провайдера синонимов",
};
