// Ukrainian

export default {
    //main.ts
    'Open Dictionary View': 'Відкрити меню словника',
    'Open Language Switcher': 'Відкрити вибір мови',

    //_constants.ts
    'Dictionary': 'Словник',

    //customContextMenu.ts
    'Cut': 'Вирізати',
    'Copy': 'Скопіювати',
    'Paste': 'Вставити',
    'Show Synonyms': 'Показати синоніми',
    'Look up': 'Знайти',

    //settingsTab.ts
    "Reset to default": "Скинути до налаштувань за замовченням",
    'Dictionary Settings': 'Налаштування словника',
    'Language': 'Мова',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': 'Мова, яку плагін використовуватиме для пошуку значень та вимови.',
    'Synonym Suggestions': 'Пропозиції синонімів',
    'Show synonyms for highlighted words': 'Показати синоніми для виділених слів',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': 'Увімкнення цієї опції дозволить плагіну аналізувати повні речення, щоб покращити пропозиції синонімів на базі контексту.',
    'Click ': 'Натисніть ',
    'here': 'сюди',
    ' for Privacy Concerns.': ' для інформації про конфіденційність.',
    'Advanced Synonym Search': 'Розширений пошук синонімів',
    'Show Options in Context Menu': 'Показати опції у контекстному меню',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': 'Активувати кастомізоване контекстне меню з опціями пошуку синонімів (доступно, якщо автоматичні підказки вимкнені) і пошуку повних визначень у бічному меню. Увага: це перезапише стандартне контекстне меню Obsidian.',  
    'Click Here': 'Натисніть сюди',
    'Definition Provider': 'Провайдер визначень',
    'The API the Plugin will use to search for Definitions.': 'API, який використовуватиме плагін для пошуку визначень.',
    'Synonym Provider': 'Провайдер синонімів',
    'The API the Plugin will use to search for Synonyms.': 'API, який використовуватиме плагін для пошуку синонімів.',
    'More Information': 'Більше інформації',
    'View Information about the API\'s and the Plugin itself.': 'Переглянути інформацію про API і плагін.',
    'More Info': 'Більше інформації',
    'Donate': 'Підтримати донатом',
    'If you like this Plugin, consider donating to support continued development:': 'Якщо вам подобається цей плагін, ви можете задонатити на підтримку подальшої розробки:',
    'Local Dictionary Folder': 'Локальна директорія для словника',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': 'Укажіть директорію, у якій зберігатимуться усі нові нотатки, створені словником. Зауважте, що ця директорія вже має існувати.',
    'Capitalize File Name': 'Починати назви файлів з великої літери',
    'If you disable this, the names of newly created files will be all lowercase.': 'Коли ця опція деактивована, усі назви новостворених файлів починатимуться з маленької літери.',
    'Filename Prefix and Suffix': 'Префікс і суфікс назви файлу',
    'Here you can add a Prefix and Suffix for your newly created Files.': 'Тут ви можете додати префікс і суфікс до ваших новостворених файлів.',
    "Prefix": "Префікс",
    "Suffix": "Суфікс",
    'Here you can edit the Template for newly created Files.': 'Тут ви можете відредагувати шаблон для новостворених файлів.',
    'Click for a List of Variables': 'Натисніть тут, щоб переглянути список змінних.',
    'Template': 'Шаблон',
    "Local-Dictionary-Builder Settings": "Налаштування локального конструктора словника",
    "Miscellaneous": "Інше",
    "Caching Settings": "Налаштування кешування",
    "Use Caching": "Використовувати кешування",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "Увімкнути або вимкнути кешування. Кешування створює напів-офлайн досвід, зберігаючи кожен результат для повторного використання.",
    'Here you can delete all cached Data.': 'Тут ви можете видалити усі закешовані дані.',
    "You currently have ": "Наразі у вас ",
    " cached Definitions and ": " закешованих визначень і ",
    " cached Synonyms.": " закешованих синонімів.",
    "Delete Cache": "Очистити кеш",
    "Delete": "Видалити",
    "Success": "Успіх",
    'Use Language specific Subfolders': "Використовувати окремі піддиректорії для різних мов",
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': "Створювати піддиректорії для кожної мови, наприклад, \"Dictionary/uk-ua/Kuchen\"",
    
    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': 'Сгенеровано Obsidian Dictionary плагіном автоматично',
    "No, keep the old File.": "Ні, залиште старий файл.",
    "Yes, overwrite the old File.": "Так, перезапишіть старий файл.",
    "A existing File with the same Name was found, do you want to overwrite it?": "Вже існує файл з такою назвою, перезаписати його?",
    "Meaning {{i}}": "Значення {{i}}",

    //infoModal.svelte
    'API Information': 'Інформація про API',
    'Definition API\'s': 'API визначень',
    'Website': 'Вебсайт',
    'Synonym API\'s': 'API синонімів',
    'Part of Speech API\'s': 'API частин мови',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': 'Цей плагін використовує <a href="https://feathericons.com/">Feather Icons</a>',

    //dictionaryView.svelte
    "Clear": "Очистити",
    "Change Language": "Змінити мову",
    "Change Provider": "Змінити провайдера",
    "Collapse Results": "Згорнути результати",
    'Enter a word': 'Введіть слово',
    'Pronunciation': 'Вимова',
    'Meanings': 'Значення',
    "Origin": "Походження",
    'New Note': 'Нова нотатка',
    "Match Case": "Match Case",
    "View Error": "Переглянути помилку",
    "Copied \"{{word}}\" to clipboard": "\"{{word}}\" скопійовано до буферу обміну",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': 'Я не можу знайти слово, яке ви шукаєте, або сервер не відповідає. Спробуйте, будь ласка, через декілька хвилин.',

    //meaningComponent.ts
    'Definition:': 'Визначення:',
    'Synonyms:': 'Синоніми:',
    'Antonyms:': 'Антоніми:',

    //modals
    "Choose a Definition Provider Service": "Обрати сервіс провайдера визначень",
    "Choose a Language": "Обрати мову",
    "Choose a Synonym Provider Service": "Обрати сервіс провайдера синонімів",
};
