// 简体中文

export default {
    //main.ts
    'Open Dictionary View': '打开查词面板',

    //_constants.ts
    'Dictionary': '词典',

    //customContextMenu.ts
    'Cut': '剪切',
    'Copy': '复制',
    'Paste': '粘贴',
    'Show Synonyms': '显示同义词',
    'Look up': '查询',

    //settingsTab.ts
    'Dictionary Settings': '词典设置',
    'Language': '语言',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': '插件会根据该语言来搜索语义以及发音',
    'Synonym Suggestions': '同义词建议',
    'Show synonyms for highlighted words': '展示被高亮的词的同义词',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': '允许该选项将会对整段文本进行分析来建议更好的同义词',
    'Click ': '点击 ',
    'here': '这里',
    ' for Privacy Concerns.': ' 来获取相关隐私解释',
    'Advanced Synonym Search': '同义词搜索进阶',
    'Show Options in Context Menu': '在右键菜单中显示选项',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': '允许自定义右键菜单来更方便搜索同义词（需要关闭自动建议）且在侧栏的词典面板展示相关释义。注意，这会覆盖掉 Obsidian 的默认右键菜单。',
    'Definition Provider': '释义来源',
    'The API the Plugin will use to search for Definitions.': '将基于该 API 去搜索释义',
    'Synonym Provider': '同义词来源',
    'The API the Plugin will use to search for Synonyms.': '将基于该 API 去搜索同义词',
    'More Information': '更多信息',
    'View Information about the API\'s and the Plugin itself.': '了解关于插件以及 API 的信息',
    'More Info': '更多信息',
    'Donate': '捐赠',
    'If you like this Plugin, consider donating to support continued development:': '如果你喜欢该插件，可以考虑打赏支持：',
    'Local Dictionary Folder': '本地词典文件夹',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': '指定词典创建的新笔记所存放的位置，注意文件夹需要存在',

    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': '由 Obsidian Dictionary Plugin 插件自动生成',
    

    //infoModal.svelte
    'API Information': 'API 信息',
    'Definition API\'s': '定义 API',
    'Website': '网站',
    'Synonym API\'s': '定义同义词 API',
    'Part of Speech API\'s': '语音 API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': '这个插件使用 <a href="https://feathericons.com/">Feather 图标</a>',

    //dictionaryView.svelte
    'Enter a word': '输入单词',
    'Pronunciation': '发音',
    'Meanings': '词义',
    'New Note': '新笔记',

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': '无法找到你搜索的单词或者服务器当前不可用，你可以几分钟后再试一下。',

    //meaningComponent.ts
    'Definition:': '词义：',
    'Synonyms:': '同义词：',
};

