// 简体中文

export default {
    //main.ts
    'Open Dictionary View': '打开查词面板',
    'Open Language Switcher': '切换语言',

    //_constants.ts
    'Dictionary': '词典',

    //customContextMenu.ts
    'Cut': '剪切',
    'Copy': '复制',
    'Paste': '粘贴',
    'Show Synonyms': '显示同义词',
    'Look up': '查询',

    //settingsTab.ts
    "Reset to default": "重置为默认设置",
    'Dictionary Settings': '词典设置',
    'Language': '语言',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': '插件会根据该语言来搜索语义以及发音',
    'Synonym Suggestions': '同义词建议',
    'Show synonyms for highlighted words': '展示被高亮的词的同义词',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': '允许该选项将会对整段文本进行分析来建议更好的同义词',
    'Click ': '点击 ',
    'here': '这里',
    ' for Privacy Concerns.': ' 来获取相关隐私解释',
    'Advanced Synonym Search': '同义词搜索进阶',
    'Show Options in Context Menu': '在右键菜单中显示选项',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': '允许自定义右键菜单来更方便搜索同义词（需要关闭自动建议）且在侧栏的词典面板展示相关释义。注意，这会覆盖掉 Obsidian 的默认右键菜单。',
    'Click Here': '点击这里',
    'Definition Provider': '释义来源',
    'The API the Plugin will use to search for Definitions.': '将基于该 API 去搜索释义',
    'Synonym Provider': '同义词来源',
    'The API the Plugin will use to search for Synonyms.': '将基于该 API 去搜索同义词',
    'More Information': '更多信息',
    'View Information about the API\'s and the Plugin itself.': '了解关于插件以及 API 的信息',
    'More Info': '更多信息',
    'Donate': '捐赠',
    'If you like this Plugin, consider donating to support continued development:': '如果你喜欢该插件，可以考虑打赏支持：',
    'Local Dictionary Folder': '本地词典文件夹',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': '指定词典创建的新笔记所存放的位置，注意文件夹需要存在',
    'Capitalize File Name': '将文件名首字母大写',
    'If you disable this, the names of newly created files will be all lowercase.': '如果你关闭这个选项，新建文件首字母将是小写。',
    'Filename Prefix and Suffix': '文件名前缀和后缀',
    'Here you can add a Prefix and Suffix for your newly created Files.': '在这里你可以为新建文件添加前缀和后缀。你可以使用 {{lang}} 变量。Here you can add a Prefix and Suffix for your newly created Files. You can use the {{lang}} variable here.',
    "Prefix": "前缀",
    "Suffix": "后缀",
    'Here you can edit the Template for newly created Files.': '在这里你可以编辑新建文档的模板。',
    'Click for a List of Variables': '点击查看变量列表',
    'Template': '模板',
    "Local-Dictionary-Builder Settings": "本地自建词典设置",
    "Miscellaneous": "其他",
    "Caching Settings": "缓存设置",
    "Use Caching": "使用缓存",
    "Enable or disable caching. Caching provides a semi-offline experience by saving every result for later use.": "启用或禁用缓存。缓存可以保存结果以供后续使用，提供接近本地保存的体验。",
    'Here you can delete all cached Data.': '在这里你可以删除所有缓存数据。',
    "You currently have ": "你目前有",
    " cached Definitions and ": " 已缓存释义与 ",
    " cached Synonyms.": " 已缓存同义词。",
    "Delete Cache": "删除缓存",
    "Delete": "删除",
    "Success": "成功",
    'Use Language specific Subfolders': '使用特定语言的子文件夹',
    'Create Subfolders for every language, e.g. "Dictionary/en-US/Cake"': '为所有语言创建子文件夹，例如"Dictionary/en-US/Cake"',

    
    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': '由 Obsidian Dictionary Plugin 插件自动生成',
    "Yes, overwrite the old File.": "好，覆盖旧文件。",
    "A existing File with the same Name was found, do you want to overwrite it?": "发现一个同名旧文件，是否覆盖？",
    "No, keep the old File.": "不，保留旧文件。",
    "Meaning {{i}}": "词义 {{i}}",
    

    //infoModal.svelte
    'API Information': 'API 信息',
    'Definition API\'s': '释义 API',
    'Website': '网站',
    'Synonym API\'s': '同义词 API',
    'Part of Speech API\'s': '语音 API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': '这个插件使用 <a href="https://feathericons.com/">Feather 图标</a>',

    //dictionaryView.svelte
    'Enter a word': '输入单词',
    "Clear": "清除",
    "Change Language": "更改语言",
    "Change Provider": "更改来源",
    "Collapse Results": "折叠结果",
    'Pronunciation': '发音',
    'Meanings': '词义',
    "Origin": "词源",
    'New Note': '新笔记',
    "View Error": "检视错误",
    "Match Case": "区分大小写",
    "Copied \"{{word}}\" to clipboard": "已复制 \"{{word}}\" 到剪贴板",

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': '无法找到你搜索的单词或者服务器当前不可用，你可以几分钟后再试一下。',

    //meaningComponent.ts
    'Definition:': '释义：',
    'Synonyms:': '同义词：',
    'Antonyms:': '反义词：',

    //modals
    "Choose a Definition Provider Service": "选择一个释义词典服务",
    "Choose a Language": "选择一种语言",
    "Choose a Synonym Provider Service": "选择一个同义词词典服务",
};

