// 繁體中文

export default {
    //main.ts
    'Open Dictionary View': '打開字典檢視',

    //_constants.ts
    'Dictionary': '字典',

    //customContextMenu.ts
    'Cut': '剪下',
    'Copy': '複製',
    'Paste': '貼上',
    'Show Synonyms': '顯示同義詞',
    'Look up': '查詢',

    //settingsTab.ts
    'Dictionary Settings': '字典設定',
    'Language': '語言',
    'The Language the Plugin will use to search for Definitions and Pronunciations.': '此插件用來查尋定義與發音的語言',
    'Synonym Suggestions': '同義詞建議',
    'Show synonyms for highlighted words': '顯示被高亮的字之同義詞',
    'Enabling this will allow the Plugin to analyze full sentences to better suggest synonyms based on the context.': '啟用該選項會讓此插件能夠分析整段文字以基於內容給出更好的同義詞建議',
    'Click ': '點擊 ',
    'here': '這裡',
    ' for Privacy Concerns.': '以查看相關隱私說明',
    'Advanced Synonym Search': '進階同義詞查詢',
    'Show Options in Context Menu': '在右鍵菜單顯示選項',
    'Enable custom Context Menu with options to search for synonyms (only if the auto suggestions are disabled) and to look up a full definition in the Sidebar. Warning: This will override Obsidian\'s default Context Menu.': '啟用包含選項的自定義右鍵菜單以搜尋同義詞（需要關閉自動建議）並在側欄查看完整定義。注意，這會覆蓋掉 Obsidian 的默認右鍵菜單。',
    'Definition Provider': '定義來源',
    'The API the Plugin will use to search for Definitions.': '此插件查詢定義所用的 API',
    'Synonym Provider': '同義詞來源',
    'The API the Plugin will use to search for Synonyms.': '此插件查詢同義詞所用的 API',
    'More Information': '更多資訊',
    'View Information about the API\'s and the Plugin itself.': '了解更多關於 API 以及此插件的資訊',
    'More Info': '更多資訊',
    'Donate': '捐款',
    'If you like this Plugin, consider donating to support continued development:': '如果你喜歡此插件，可以考慮斗內支持開發',
    'Local Dictionary Folder': '本地字典資料夾',
    'Specify a Folder, where all new Notes created by the Dictionary are placed. Please note that this Folder needs to already exist.': '指定所有字典新創的筆記存放的資料夾，注意該資料夾必須已經存在',

    //localDictionaryBuilder.ts
    'Autogenerated by Obsidian Dictionary Plugin': '由 Obsidian Dictionary 插件自動生成',
    

    //infoModal.svelte
    'API Information': 'API 資訊',
    'Definition API\'s': '定義 API',
    'Website': '網站',
    'Synonym API\'s': '同義詞 API',
    'Part of Speech API\'s': '語音 API',
    'This Plugin is using <a href="https://feathericons.com/">Feather Icons</a>': '這個插件使用 <a href="https://feathericons.com/">Feather 圖示</a>',

    //dictionaryView.svelte
    'Enter a word': '輸入單字',
    'Pronunciation': '發音',
    'Meanings': '字義',
    'New Note': '新筆記',

    //errorComponent.ts
    'I can\'t find the word you are looking for or the server can\'t be reached. You can try again in a few minutes.': '無法找到你輸入的字，或是無法連上伺服器。可以過幾分鐘再試。',

    //meaningComponent.ts
    'Definition:': '定義：',
    'Synonyms:': '同義詞：',
};
